# Custom Language File for Launcher Customizer

[ejs.app]
title = "Usami Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Usasyuu/UsamiLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/channels/889873666714792046/1107109257175904327"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "ようこそ！ Usamiランチャーへ！"
welcomeDescription = "このランチャーでは、自動的に適切なModをインストールしてサーバーに入ることができます。"
welcomeDescCTA = "宇佐見柊士"
